"""More columns for product table

Revision ID: 0c8ceccc601e
Revises: c1e4a1cefd36
Create Date: 2025-12-25 00:51:39.470142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8ceccc601e'
down_revision: Union[str, Sequence[str], None] = 'c1e4a1cefd36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_per_m2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('thickness_mm', sa.Integer(), nullable=True),
    sa.Column('max_width', sa.Integer(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('min_width_mm', sa.Integer(), nullable=True),
    sa.Column('min_height_mm', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
