"""More columns for product table

Revision ID: 2bf9d7508dd5
Revises: e332d5993fbf
Create Date: 2025-12-25 00:05:47.648651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf9d7508dd5'
down_revision: Union[str, Sequence[str], None] = 'e332d5993fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('thickness_mm', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('min_width_mm', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('min_height_mm', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'min_height_mm')
    op.drop_column('products', 'min_width_mm')
    op.drop_column('products', 'thickness_mm')
    # ### end Alembic commands ###
