"""max width, max_len

Revision ID: 2d1b044ad3c9
Revises: ab3cd5c2f1ef
Create Date: 2025-12-24 00:02:04.026872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d1b044ad3c9'
down_revision: Union[str, Sequence[str], None] = 'ab3cd5c2f1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('max_width', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('max_length', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'product_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'max_length')
    op.drop_column('products', 'max_width')
    # ### end Alembic commands ###
