"""add email verification fields

Revision ID: 50202fe48553
Revises: 7cb878975778
Create Date: 2025-12-20 19:09:44.544097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50202fe48553'
down_revision: Union[str, Sequence[str], None] = '7cb878975778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('verify_code_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verify_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('verify_code_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verify_code_sent_at')
    op.drop_column('users', 'verify_code_expires_at')
    op.drop_column('users', 'verify_code_hash')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
