"""is_active для всех видов обработок

Revision ID: 560522c0b59f
Revises: 6ea40d56bbd3
Create Date: 2025-12-26 23:17:41.686383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560522c0b59f'
down_revision: Union[str, Sequence[str], None] = '6ea40d56bbd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facet_prices', sa.Column('is_active', sa.Boolean(), nullable=True, server_default=sa.true()))
    op.drop_constraint(op.f('uq_facet_shape_width'), 'facet_prices', type_='unique')
    op.add_column('glass_edge_processing_prices', sa.Column('is_active', sa.Boolean(), nullable=True, server_default=sa.true()))
    op.add_column('tempering_prices', sa.Column('is_active', sa.Boolean(), nullable=True, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tempering_prices', 'is_active')
    op.drop_column('glass_edge_processing_prices', 'is_active')
    op.create_unique_constraint(op.f('uq_facet_shape_width'), 'facet_prices', ['shape', 'facet_width_mm'], postgresql_nulls_not_distinct=False)
    op.drop_column('facet_prices', 'is_active')
    # ### end Alembic commands ###
