"""fix for product table

Revision ID: 6ea40d56bbd3
Revises: 0c8ceccc601e
Create Date: 2025-12-25 00:59:12.884849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ea40d56bbd3'
down_revision: Union[str, Sequence[str], None] = '0c8ceccc601e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facet_prices', 'thickness_mm')
    op.drop_constraint(op.f('tempering_prices_thickness_mm_key'), 'tempering_prices', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('tempering_prices_thickness_mm_key'), 'tempering_prices', ['thickness_mm'], postgresql_nulls_not_distinct=False)
    op.add_column('facet_prices', sa.Column('thickness_mm', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
