"""fixes carts db4

Revision ID: b48e3fa6580a
Revises: a26995fdf215
Create Date: 2025-12-28 01:18:36.733237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48e3fa6580a'
down_revision: Union[str, Sequence[str], None] = 'a26995fdf215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('width_mm', sa.Integer(), nullable=False),
    sa.Column('length_mm', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('edge_id', sa.Integer(), nullable=True),
    sa.Column('facet_id', sa.Integer(), nullable=True),
    sa.Column('tempering_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edge_id'], ['glass_edge_processing_prices.id'], ),
    sa.ForeignKeyConstraint(['facet_id'], ['facet_prices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tempering_id'], ['tempering_prices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carts')
    # ### end Alembic commands ###
