"""More tables for products

Revision ID: e332d5993fbf
Revises: 5bc98f2661e3
Create Date: 2025-12-24 23:50:10.066998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e332d5993fbf'
down_revision: Union[str, Sequence[str], None] = '5bc98f2661e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facet_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shape', sa.String(), nullable=False),
    sa.Column('thickness_mm', sa.Integer(), nullable=True),
    sa.Column('facet_width_mm', sa.Integer(), nullable=False),
    sa.Column('price_rub', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glass_edge_processing_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edge_shape', sa.String(), nullable=False),
    sa.Column('edge_type', sa.String(), nullable=False),
    sa.Column('thickness_mm', sa.Integer(), nullable=False),
    sa.Column('price_rub', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tempering_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thickness_mm', sa.Integer(), nullable=False),
    sa.Column('price_rub', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tempering_prices')
    op.drop_table('glass_edge_processing_prices')
    op.drop_table('facet_prices')
    # ### end Alembic commands ###
